In [1]:
#Basic If-Else Statements:

In [6]:
#1. Write a Python program to check if a given number is positive or negative.
#ans:

x=int(input("enter your number:"))
if x>=0:
    print("the enetered number is positive")
else:
    print("the entered number is negative")

enter your number: -1


the entered number is negative


In [10]:
#2. Create a program that determines if a person is eligible to vote based on their age.
#ans:

x=int(input("enter the voter age :"))
if x>=18<=130:
    print("this person is eligible for vote")
else:
    print("this person not eligible for vote")
    

enter the voter age 131


this person is eligible for vote


In [22]:
#3. Develop a program to find the maximum of two numbers using if-else statements.
#ans:

a=int(input("enter your a value :"))
b=int(input("enter your b value :"))
if a>b:
    print("maximum number is a value")
else:
      print("maximum number is 'b' value")

enter your a value : 5
enter your b value : 6


maximum number is 'b' value


In [6]:
#4. Write a Python script to classify a given year as a leap year or not.
#ans:
year=int(input("enter the year:"))
if ((year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)):
    print("it is the leap year")
else:
    print("not a leap year")
    

enter the year: 2024


it is the leap year


In [8]:
#5. Create a program that checks whether a character is a vowel or a consonant.
#ans:
char=input("enter the letter :")
vowels=['a','i','e','o','u','A','I','E','O','U']
if char in vowels:
    print("it is a vowel")
else:
    print("it is a constant")

enter the letter : B


it is a constant


In [15]:
#6. Implement a program to determine whether a given number is even or odd.
#ans:
x=int(input("enter the digit"))
if x%2==0:
    print("it is a even number")
else:
    print("it is a odd number")

enter the digit 5


it is a odd number


In [11]:
#7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.
#ans:
#ans:
def  my_abs(value):
    if value<0:
        return -value
    return value
my_abs(-50)

50

In [15]:
#8. Develop a program that determines the largest of three given numbers using if-else statements.
#ans:
a=int(input("enter the a value:"))
b=int(input("enter the b value:"))
c=int(input("enter the c value:"))
if a>=b>=c:
    print("a is the maximum value :",a)
    if b>=c>=a:
        print("b is the maximum value :",b)
else :
    print("c is the maximum value:",c)

enter the a value: 5
enter the b value: 4
enter the c value: 3


a is the maximum value : 5


In [29]:
#9. Create a program that checks if a given string is a palindrome.
x=input("enter the string :")
if x==x[::-1]:
    print("this is paindrome")
else :
    print("this is not a palindrome")

enter the string : RAPER


this is not a palindrome


In [26]:
#10. Write a Python program to calculate the grade based on a student's score.
score=int(input("enter the score"))
if score>=35:
    print("the grade : C & need to do hard work")
if score>=50:
    print("the grade : C+ & clever performance")
if score>=75:
    print("the grade : A+ & excellent performance")
if score>=85:
    print("the grade : A & clever performance")
if score>=90:
    print("the grade : O & out standing performance")
else :
    print("the candidate is failed")

enter the score 35


the grade : D & need to do hard work
the candidate is failed


In [27]:
#Nested If-Else Statements:

In [44]:
#11. Write a program to find the largest among three numbers using nested if-else statements.
a=int(input("enter the value of a:"))
b=int(input("enter the value of b:"))
c=int(input("enter the value of c:"))
if a>b:
    if a>c:
        print("a is the maximum value:",a)
    else:
        print("c is the maximum value:",c)
else:
    if b>c:
        print("b is the maximum value:",b)
    else:
        print("c is the maximum value:",c)
    

enter the value of a: 88
enter the value of b: 98
enter the value of c: 56


b is the maximum value: 98


In [74]:
#12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.
x=int(input("enter the vlaue of x"))
y=int(input("enter the value of y"))
z=int(input("enter the value of z"))
if x==y==z:
    print("this is an equilateral triangle")
else:
    if x==y or x==z or y==z:
        print("this is an iscosceles triangle")
    else:
        print("this is an scalene triangle")

enter the vlaue of x 20
enter the value of y 20
enter the value of z 30


this is an iscosceles triangle


In [22]:
#13. Develop a program that checks if a year is a leap year and also if it is a century year.
year=int(input("enter the year :"))
def check_leap_year(year):
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                print(f"{year} is a leap year")
            else:
                print(f"{year} is not a leap year")
        else:
            print(f"{year} is a leap year")
    else:
        print(f"{year} is not a leap year")
        
        
def find_century(year): 
    
    # No negative value is allow for year 
    if (year <= 0): 
        print("0 and negative is not allow for a year") 
          
    # If year is between 1 to 100 it 
    # will come in 1st century 
    if (year <= 100): 
        print("1st century") 
    if (year % 100 == 0): 
        print(year // 100,"century") 
    else: 
        print(year // 100 + 1,"century") 
  
find_century(year)
check_leap_year(year)


enter the year : 2024


21 century
2024 is a leap year


In [35]:
#14. Write a Python script to determine if a number is positive, negative, or zero.
x=int(input("enter the number:"))
if x>=0:
    if x==0:
        print("the number is Zero :",x)
    else:
        print("the number is Positive :",x)
else:
    if x<0:
        print("the number is equal to zero :",x)
        

enter the number: 0


the number is Zero : 0


In [14]:
#15. Create a program to check if a person is a teenager (between 13 and 19 years old).
x=int(input("enter the person age:"))
if 0<=x<=12:
    print("this is kid")
    if 13<=x<=19:
        print("this is a teenager")
else:
    print("this is a not a teenager")

enter the person age: 25


this is a not a teenager


In [25]:
#16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).
def triangleType(a, b, c):
    sa = pow(a, 2)
    sb = pow(b, 2)
    sc = pow(c, 2)
    if (sa == sc + sb or sb == sa+sc or sc == sa+sb):
        print("Right-angled triangle")
    if (sa > sc + sb or sb > sa+sc or sc > sa+sb):
        print("Obtuse-angled triangle")
    else:
        print("Acute-angled triangle")
        
a = int(input("Enter side a: "))
b = int(input("Enter side b: "))
c = int(input("Enter side c: "))
triangleType(a, b, c)

Enter side a:  60
Enter side b:  90
Enter side c:  30


Obtuse-angled triangle


In [39]:
#17. Write a Python program to calculate the roots of a quadratic equation.
# Python program to find roots of quadratic equation  
import math  
  
  
# function for finding roots  
def findRoots(a, b, c):  
  
    dis_form = b * b - 4 * a * c  
    sqrt_val = math.sqrt(abs(dis_form))  
  
  
    if dis_form > 0:  
        print(" real and different roots ")  
        print((-b + sqrt_val) / (2 * a))  
        print((-b - sqrt_val) / (2 * a))  
  
    if dis_form == 0:  
        print(" real and same roots")  
        print(-b / (2 * a))  
  
  
    else:  
        print("Complex Roots")  
        print(- b / (2 * a), " + i", sqrt_val)  
        print(- b / (2 * a), " - i", sqrt_val)  
  
  
a = int(input('Enter a:'))  
b = int(input('Enter b:'))  
c = int(input('Enter c:'))  
  
# If a is 0, then incorrect equation  
if a == 0:
        print("Input correct quadratic equation")  
else:  
    findRoots(a, b, c)  

Enter a: 5
Enter b: 5
Enter c: 5


Complex Roots
-0.5  + i 8.660254037844387
-0.5  - i 8.660254037844387


In [50]:
"""18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
for Tuesday, etc.)."""
#ans:
day=int(input("enter a number 1 to 7:"))
if day==1:
    print(day, "is Sunday")
if day==2:
    print(day, "is Sunday")
if day == 3:
    print(day, "is Tuesday")
if day==4:
    print(day,"is wednesday")
if day==5:
    print(day, "is thursday")
if day==6:
    print(day, "is friday")
if day==7:
    print(day,"is saturday")
else:
    print("wrong input given")

enter a number 1 to 7: 8


wrong input given


In [57]:
#19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.
#ans:
year=int(input("enter the year:"))
if ((year % 4 == 0 and year % 100 != 0)):
    if(year % 400 == 0):
        print("it is the leap year")
else:
        print("not a leap year")
    

enter the year: 2024


In [71]:
#20. Develop a program that checks if a given number is prime or not using nested if-else statements.
#ans:
# Program to check if a number is prime or not

num=int(input("enter a num"))

# To take input from the user
#num = int(input("Enter a number: "))

# define a flag variable
flag = False

if num == 1:
    print(num, "is not a prime number")
elif num > 1:
    # check for factors
    for i in range(2, num):
        if (num % i) == 0:
            # if factor is found, set flag to True
            flag = True
            # break out of loop
            break

    # check if flag is True
    if flag:
        print(num, "is not a prime number")
    else:
        print(num, "is a prime number")

enter a num 4


4 is not a prime number


In [72]:
#Elif Statements:

In [14]:
#21. Write a Python program to assign grades based on different ranges of scores using elif statements.
#ans:

x=int(input("enter the score :"))


if 35<=x<=50:
    print("Grade 'C' & Need to do hardwork")
elif 51<=x<=75:
        print("Garde B & good performance")
elif 76<=x<=85:
        print("Grade A & clever performance")
elif 86<=x<=95:
        print("Grade O & excellent performance")
elif 96<=x<=100:
        print("Grade O+ & out standing performance")
else:
    if 96<=x<=100:
        print("the Candidate is failed")

enter the score : 56


Garde B & good performance


In [16]:
#22. Implement a program to determine the type of a triangle based on its angles.
#ans:
def triangleType(a, b, c):
    sa = pow(a, 2)
    sb = pow(b, 2)
    sc = pow(c, 2)
    if (sa == sc + sb or sb == sa+sc or sc == sa+sb):
        print("Right-angled triangle")
    elif (sa > sc + sb or sb > sa+sc or sc > sa+sb):
        print("Obtuse-angled triangle")
    else:
        print("Acute-angled triangle")
        
a = int(input("Enter side a: "))
b = int(input("Enter side b: "))
c = int(input("Enter side c: "))
triangleType(a, b, c)


Enter side a:  60
Enter side b:  70
Enter side c:  80


Acute-angled triangle


In [23]:
"""23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
elif statements."""
#ans:
#BMI
x=int(input("enter the persons weight :"))
if 20<=x<=40:
    print("this person is underweight")
elif 41<=x<=60:
    print("this person is normalweight")
elif 61<=x<=79:
    print("this person is over weight")
elif 80<=x<=90:
    print("this person is overweight with obese class I ")
elif 90<=x<=100:
    print("this person is overweight with obese class II ")
elif 100<=x<=600:
    print("this person is overweight with obese class III ")
else :
    print("enter the valid weight number")

enter the persons weight : 100


this person is overweight with obese class II 


In [28]:
"""24. Create a program that determines whether a given number is positive, negative, or zero using elif
statements."""
#ans:
x=int(input("enter the number :"))
if x>0:
    print("the entered value is Positive :",x)
elif x<0:
    print("the number is negative",x)
elif x==0:
    print("the number is equal to zero",x)
else:
    print("enter the valid number")

enter the number : -100


the number is negative -100


In [36]:
"""25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
statements."""
#ans:
x=input("enter your word:")
if x.isupper():
    print("word is in uppercase : ",x)
elif x.islower():
    print("word is lowercase : ",x)
elif x.isdigit():
    print("this is numeric",x)
else:
    print("word is specialcase : ",x)
    

enter your word: ali


word is lowercase :  ali


In [38]:
"""26. Implement a program to calculate the discounted price based on different purchase amounts using elif
statements."""
#ans:
p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  5555


Discount Amount = 55.50
Net Bill Amount = 5499.50


In [39]:
"""#27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
statements."""
#ans:
unit = int(input("Enter your unit: "))
if unit <= 100:
    bill = unit * 3.46
elif unit >= 101 and unit <= 300:
    bill = 346 + ((unit - 100) * 7.43)
elif unit >= 301 and unit <= 500:
    bill = 346 + 1486 + ((unit - 300) * 10.32)
else:
    bill = 346 + 1486 + 2064 + ((unit - 500) * 11.71)
print("Bill Per Unit:",bill)
bill = bill + (unit*1.45)
print("Bill after adding Line rent:",bill)
bill = bill + 100
print("Bill after adding Meter rent:",bill)
bill = bill + (bill*0.16)
print("Total Bill after adding tax:",bill)

Enter your unit:  50000


Bill Per Unit: 583541.0
Bill after adding Line rent: 656041.0
Bill after adding Meter rent: 656141.0
Total Bill after adding tax: 761123.56


In [40]:
"""28. Create a program to determine the type of quadrilateral based on its angles and sides using elif
statements."""
#ans:
print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 


x:  60
y:  60
z:  60


Equilateral triangle


In [41]:
#29. Write a Python script to determine the season based on a user-provided month using elif statements.
#ans:
month = input("Input the month (e.g. January, February etc.): ")
day = int(input("Input the day: "))

if month in ('January', 'February', 'March'):
	season = 'winter'
elif month in ('April', 'May', 'June'):
	season = 'spring'
elif month in ('July', 'August', 'September'):
	season = 'summer'
else:
	season = 'autumn'

if (month == 'March') and (day > 19):
	season = 'spring'
elif (month == 'June') and (day > 20):
	season = 'summer'
elif (month == 'September') and (day > 21):
	season = 'autumn'
elif (month == 'December') and (day > 20):
	season = 'winter'

print("Season is",season)

Input the month (e.g. January, February etc.):  january
Input the day:  25


Season is autumn


In [45]:
"""30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
elif statements."""
#ans:

month = int(input("enter the month number"))
year = int(input("enter the year"))
if(month == 1 or month == 3 or month == 5 or month == 7 or month == 8 or month == 10 or month == 12):
	print("Number of days is 31")
elif((month == 2) and ((year%400==0) or (year%4==0 and year%100!=0))):	
	print("Number of days is 29 and it is a leap year")
elif(month == 2):
	print(" of days is 28")
else:
	print("Number of days is 30")

enter the month number 2
enter the year 2024


Number of days is 29 and it is a leap year


In [46]:
###Basic Level:

In [4]:
#1. Write a Python program that checks if a given number is positive, negative, or zero.
#ans:
x=int(input("enter the number : "))
if x>0:
    print("the given number is Positive :",x)
elif x<0:
    print("the given number is Negative :",x)
elif x==0:
    print("the given number is Zero :",x)
else:
    print("enter the valid number :")

enter the number :  55


the given number is Positive : 55


In [12]:
#2. Create a program to determine if a person is eligible to vote based on their age.
#ans:
x=int(input("enter the voters age : "))
if x>=18:
    print("this voter is eligible for voting")
else:
    if 0<=x<=18:
        print("this person is not eligible")


enter the voters age :  12


this person is not eligible


In [13]:
#3. Write a program to find the maximum of two given numbers using conditional statements.
#ans:
a=int(input("enter the a value"))
b=int(input("enter the b value"))
if a>b:
    print("Maximum number is a : ",a)
else:
    print("maximum number is b : ",b)

enter the a value 5
enter the b value 6


maximum number is b :  6


In [14]:
#4. Develop a program that calculates the grade of a student based on their exam score.
#ans:
x=int(input("enter the score :"))


if 35<=x<=50:
    print("Grade 'C' & Need to do hardwork")
elif 51<=x<=75:
        print("Garde B & good performance")
elif 76<=x<=85:
        print("Grade A & clever performance")
elif 86<=x<=95:
        print("Grade O & excellent performance")
elif 96<=x<=100:
        print("Grade O+ & out standing performance")
else:
    if 96<=x<=100:
        print("the Candidate is failed")

enter the score : 55


Garde B & good performance


In [15]:
#5. Create a program that checks if a year is a leap year or not.
#ans:
year=int(input("enter the year:"))
if ((year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)):
    print("it is the leap year")
else:
    print("not a leap year")

enter the year: 2024


it is the leap year


In [16]:
#6. Write a program to classify a triangle based on its sides' lengths.
#ans:
print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 


x:  60
y:  60
z:  60


Equilateral triangle


In [42]:
#7. Build a program that determines the largest of three given numbers.
#ans:
a=int(input("enter the a value : "))
b=int(input("enter the b value : "))
c=int(input("enter the c value : "))
if a>b:
    print("a is the maximum value",a)
elif a>c:
    print("a is the maximum value",a)
elif b>c:
    print("b is the maximum value",b)
else:
    print("c is the maximum value",c)

enter the a value :  50
enter the b value :  40
enter the c value :  56


a is the maximum value 50


In [22]:
#8. Develop a program that checks whether a character is a vowel or a consonant.
#ans:
char=input("enter the letter :")
vowels=['a','i','e','o','u','A','I','E','O','U']
if char in vowels:
    print("it is a vowel")
else:
    print("it is a constant")

enter the letter : A


it is a vowel


In [23]:
#9. Create a program to calculate the total cost of a shopping cart based on discounts.
#ans:
p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  5006


Discount Amount = 0.60
Net Bill Amount = 5005.40


In [28]:
#10. Write a program that checks if a given number is even or odd.
#ans:
x=int(input("enter the number : "))
if x%2==0:
    print("given number is even",x)
else:
    print("given number is odd",x)


enter the number :  4


given number is even 4


In [29]:
###Intermediate Level:

In [33]:
#11. Write a program that calculates the roots of a quadratic equation .
#ans:
import math
# function for finding roots  
def findRoots(a, b, c):  
  
    dis_form = b * b - 4 * a * c  
    sqrt_val = math.sqrt(abs(dis_form))  
  
  
    if dis_form > 0:  
        print(" real and different roots ")  
        print((-b + sqrt_val) / (2 * a))  
        print((-b - sqrt_val) / (2 * a))  
  
    if dis_form == 0:  
        print(" real and same roots")  
        print(-b / (2 * a))  
  
  
    else:  
        print("Complex Roots")  
        print(- b / (2 * a), " + i", sqrt_val)  
        print(- b / (2 * a), " - i", sqrt_val)  
  
  
a = int(input('Enter a:'))  
b = int(input('Enter b:'))  
c = int(input('Enter c:'))  
  
# If a is 0, then incorrect equation  
if a == 0:
        print("Input correct quadratic equation")  
else:  
    findRoots(a, b, c)  

Enter a: 5
Enter b: 5
Enter c: 5


Complex Roots
-0.5  + i 8.660254037844387
-0.5  - i 8.660254037844387


In [37]:
#12. Create a program that determines the day of the week based on the day number (1-7).
#ans:
day=int(input("enter a number 1 to 7:"))
if day==1:
    print(day, "is Sunday")
elif day==2:
    print(day, "is Sunday")
elif day == 3:
    print(day, "is Tuesday")
elif day==4:
    print(day,"is wednesday")
elif day==5:
    print(day, "is thursday")
elif day==6:
    print(day, "is friday")
elif day==7:
    print(day,"is saturday")
else:
    print("wrong input given")

enter a number 1 to 7: 1


1 is Sunday


In [40]:
#13. Develop a program that calculates the factorial of a given number using recursion.
#ans:
def recur_factorial(n):
    if n == 1:
        return n  
    else:
        return n*recur_factorial(n-1)  
# take input from the user  
num = int(input("Enter a number: "))  
# check is the number is negative  
if num < 0:  
   print("Sorry, factorial does not exist for negative numbers")  
elif num == 0:  
   print("The factorial of 0 is 1")  
else:  
   print("The factorial of",num,"is",recur_factorial(num))  

Enter a number:  5


The factorial of 5 is 120


In [43]:
#14. Write a program to find the largest among three numbers without using the `max()` function.
#ans:
a=int(input("enter the value of a:"))
b=int(input("enter the value of b:"))
c=int(input("enter the value of c:"))
if a>b:
    if a>c:
        print("a is the maximum value:",a)
    else:
        print("c is the maximum value:",c)
else:
    if b>c:
        print("b is the maximum value:",b)
    else:
        print("c is the maximum value:",c)
    

enter the value of a: 50
enter the value of b: 40
enter the value of c: 56


c is the maximum value: 56


In [50]:
#15. Create a program that simulates a basic ATM transaction menu.
#ans:
import time as t


user_pin = 9876
user_balance = 97432.50
user_name = "Ms. ABC"
print("Welcome to your bank account", user_name, end = "\n\n")

choice = 9

while (True):
    print("\t\t0. Logout and Exit")
    print("\t\t1. View Account Balance")
    print("\t\t2. Withdraw Cash")
    print("\t\t3. Deposit Cash")
    print("\t\t4. Change PIN")
    print("\t\t5. Return Card")
    choice = int(input("Enter number to proceed > "))
    print("\n\n")

    if choice == 0:
        print("Exiting...")
        t.sleep(2)
        print("You have been logged out. Thank you!\n\n")
        break

    elif choice in (1,2,3,4,5):
        num_of_tries = 3
        while (num_of_tries!=0):
            input_pin = int(input("Please enter your 4-digit PIN > "))

            if input_pin == user_pin:
                print("Account auhtorized!\n\n")

                if choice == 1:
                    print("Loading Account Balance...")
                    t.sleep(1.5)
                    print("Your current balance is Rs.", user_balance, end = "\n\n\n")
                    break
                elif choice == 2:
                    print("Opening Cash Withdrawal...")
                    t.sleep(1.5)

                    while(True):
                        withdraw_amt = float(input("Enter the amount you wish to withdraw > "))

                        if withdraw_amt>user_balance:
                            print("Can't withdraw Rs.", withdraw_amt)
                            print("Please enter a lower amount!")
                            continue

                        else:
                            print("Withdrawing Rs.", withdraw_amt)
                            confirm = input("Confirm? Y/N > ")
                            if confirm in ('Y', 'y'):
                                user_balance-=withdraw_amt
                                print("Amount withdrawn - Rs.", withdraw_amt)
                                print("Remaining balance - Rs.", user_balance, end = "\n\n\n")
                                break

                            else:
                                print("Cancelling transaction...")
                                t.sleep(1)
                                print("Transaction Cancelled!\n\n")
                                break

                    break

                elif choice == 3:
                    print("Loading Cash Deposit...")
                    t.sleep(1.5)

                    deposit_amt = float(input("Enter the amount you wish to deposit > "))
                    print("Depositing Rs.", deposit_amt)
                    confirm = input("Confirm? Y/N > ")
                    if confirm in ('Y', 'y'):
                        user_balance+=deposit_amt
                        print("Amount deposited - Rs.", deposit_amt)
                        print("Updated balance - Rs.", user_balance, end = "\n\n\n")
                    else:
                        print("Cancelling transaction...")
                        t.sleep(1)
                        print("Transaction Cancelled!\n\n")

                    break


                elif choice == 4:
                    print("Loading PIN Change...")
                    t.sleep(1.5)

                    pin_new = int(input("Enter your new PIN > "))

                    print("Changing PIN to", pin_new)
                    confirm = input("Confirm? Y/N > ")
                    if confirm in ('Y', 'y'):
                        user_pin = pin_new
                        print("PIN changed successfully! \n\n")
                    else:
                        print("Cancelling PIN change...")
                        t.sleep(1)
                        print("Process Cancelled!\n\n")

                    break

                else:
                    print("Loading Card Return...")
                    t.sleep(1.5)

                    print("Returning your ATM Card")
                    confirm = input("Confirm? Y/N > ")
                    if confirm in ('Y', 'y'):
                        print("Card returned successfully! \n\n")
                    else:
                        print("Cancelling process...")
                        t.sleep(1)
                        print("Process Cancelled!\n\n")

                    break

            else:
                num_of_tries-=1
                print("PIN incorrect! Number of tries left -", num_of_tries, end = "\n\n")

        else:
            print("Exiting...")
            t.sleep(2)
            print("You have been logged out. Thank you!\n\n")
            break


    else:
        print("Invalid input!")
        print("\t\t0. Enter 0 to Logout and Exit!")
        continue

Welcome to your bank account Ms. ABC

		0. Logout and Exit
		1. View Account Balance
		2. Withdraw Cash
		3. Deposit Cash
		4. Change PIN
		5. Return Card


Enter number to proceed >  1


Please enter your 4-digit PIN >  9876


Account auhtorized!


Loading Account Balance...
Your current balance is Rs. 97432.5


		0. Logout and Exit
		1. View Account Balance
		2. Withdraw Cash
		3. Deposit Cash
		4. Change PIN
		5. Return Card


Enter number to proceed >  1


Please enter your 4-digit PIN >  9876


Account auhtorized!


Loading Account Balance...
Your current balance is Rs. 97432.5


		0. Logout and Exit
		1. View Account Balance
		2. Withdraw Cash
		3. Deposit Cash
		4. Change PIN
		5. Return Card


Enter number to proceed >  0





Exiting...
You have been logged out. Thank you!




In [45]:
#16. Build a program that checks if a given string is a palindrome or not.
#ans:
x=input("enter the word")
if x==x[::-1]:
    print(" the entered was is palindrome")
else:
    print("the word is not a palindrome")
    

enter the word ali


the word is not a palindrome


In [10]:
#17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.
#ans:
# Python program to get average of a list 
def Average(lst): 
	return sum(lst) / len(lst) 

# Driver Code 
lst = [15, 9, 55, 41, 35, 20, 62, 49] 
average = Average(lst) 

# Printing average of the list 
print("Average of the list =", round(average, 2)) 


Average of the list = 35.75


In [46]:
#18. Develop a program that converts a given temperature from Celsius to Fahrenheit.
#ans:
# Temperature in celsius degree
celsius = 47

# Converting the temperature to
# fehrenheit using the formula
fahrenheit = (celsius * 1.8) + 32

# printing the result
print('%.2f Celsius is equivalent to: %.2f Fahrenheit'
	% (celsius, fahrenheit))


47.00 Celsius is equivalent to: 116.60 Fahrenheit


In [42]:
#19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.
#ans:
a=int(input("enter the a value: "))
b=int(input("enter the b value: "))
char=input("enter any operation add,sub,mul,div")
if char=="add":
    result=a+b
elif char=="sub":
    result=a-b
elif char=="mul":
    result=a*b
elif char=="div":
    result=a/b
else:
    print("input is not recognized")
print(a,char,b,result)

enter the a value:  5
enter the b value:  5
enter any operation add,sub,mul,div div


5 div 5 1.0


In [44]:
#20. Write a program that determines the roots of a cubic equation using the Cardano formula.
#ans:
a=int(input("enter the a value: "))
b=int(input("enter the b value: "))
c=int(input("enter the c value: "))
# Function to find the cubic equation
# whose roots are a, b and c
def findEquation(a, b, c):
     
    # Find the value of coefficient
    X = (a + b + c);
    Y = (a * b) + (b * c) + (c * a);
    Z = (a * b * c);
 
    # Print the equation as per the
    # above coefficients
    print("x^3 - " , X ,
          "x^2 + " ,Y ,
          "x - " , Z , " = 0");
 
# Driver Code
if __name__ == '__main__':
     
    a = 5;
    b = 2;
    c = 3;
 
    # Function Call
    findEquation(a, b, c);

enter the a value:  5
enter the b value:  6
enter the c value:  7


x^3 -  10 x^2 +  31 x -  30  = 0


In [45]:
###Advanced Level:

In [12]:
#21. Create a program that calculates the income tax based on the user's income and tax brackets.
#ans:

def calculate(amount,percent):
    return(amount*percent)/100
def calculate_income_tax(total_income:float)->float:
    if total_income<=25000:
        return 0
    elif total_income <=50000:
        return calculate(total_income-250000,5)
    elif total_income<=750000:
        return calculate(total_income-750000,10)+12500
    elif total_income <=1250000:
        return calculate(total_income-1000000,20)+75000
    elif total_incme<=1500000:
        return calculate(total_income-1250000,25)+125000
    else:
        return calculate(total_income-1500000,30)+187500
    
    
    if __name__=='__main__':
        total_income=float(input("what's your \annualincome?\n>>>"))
        tax=claculate_income_tax(total_income)
        print(f"total taxapplicableat \₹{total_income}is ₹{tax}")

In [22]:
#21. Create a program that calculates the income tax based on the user's income and tax brackets.
#ans:
def calculate(amount, percent): 
	return (amount * percent) / 100

def calculate_income_tax(total_income: 
						float) -> float: 

	if total_income <= 250000: 
		return 0
	elif total_income <= 500000: 
		return calculate(total_income -
						250000, 5) 
	elif total_income <= 750000: 
		return calculate(total_income -
						500000, 10) + 12500
	elif total_income <= 1000000: 
		return calculate(total_income -
						750000, 15) + 37500
	elif total_income <= 1250000: 
		return calculate(total_income -
						1000000, 20) + 75000
	elif total_income <= 1500000: 
		return calculate(total_income -
						1250000, 25) + 125000
	else: 
		return calculate(total_income -
						1500000, 30) + 187500


if __name__ == '__main__': 
	total_income = float(input("What's your annual income ")) 
	tax = calculate_income_tax(total_income) 
	print(f"Total tax applicable at ₹ {total_income} is ₹ {tax}") 


What's your annual income  500000


Total tax applicable at ₹ 500000.0 is ₹ 12500.0


In [16]:
#22. Write a program that simulates a rock-paper-scissors game against the computer.
#ans:
import random
options=["rock","paper","scissor"]
user_choice=input("Enter your choice :")
computer_choice=random.choice(options)
print("you chose:",user_choice)
print("computer_chose:",computer_choice)
if user_choice==computer_choice:
    print("its tie")
elif user_choice=="rock" and computer_choice=="paper":
    print("computer wins")
elif user_choice=="rock" and computer_choice=="scissor":
    print("computer wins")
elif user_choice=="scissor" and computer_choice=="paper":
    print("you win")
else:
    print("compuer wins")

Enter your choice : scissor


you chose: scissor
computer_chose: paper
you win


In [35]:
#23. Develop a program that generates a random password based on user preferences (length, complexity).
#ans:
import string
import random
#getting password length
length=int(input("enter the password length :"))
print('''choice character set for a pasword from these:
          1.Letters
          2.Special characters
          3.Digits
          4.exit''')
characterList=""
#getting charcter set  password
while(True):
    choice = int(input("pick a number :"))
    if (choice==1):
        
        #adding letters to possible characters
        characterList+=string.ascii_letters
    elif(choice==2):
        
        #adding special characters to possible
        #characters
        characterList+=string.punctuation
    elif(choice==3):
        #adding special characters to possible
        #characters
        characterList+=string.digits
    elif(choice==4):
        break
    else:
        print("please pick a valid optional!")
        
        
password=[]
for i in range(length):
    randomchar=random.choice(characterList)
    password.append(randomchar)
print("the random password is : " +"".join(password))

enter the password length : 10


choice character set for a pasword from these:
          1.Letters
          2.Special characters
          3.Digits
          4.exit


pick a number : 3
pick a number : 1
pick a number : 4


the random password is : jKyQHoU3W2


In [15]:
#24. Create a program that implements a simple text-based adventure game with branching scenarios.
#ans:
answer_yes = ["Yes", "Y", "yes", "y"]
answer_no = ["No", "N", "no", "n"]

print("""
WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)
""")

ans1 = input(">>")

if ans1 in answer_yes:
    print("\nAfter 2 minutes, the Police came to your house, and ask you that whether the thief is in your house or not. Will you say (Yes / No)\n")

    ans2 = input(">>")

    if ans2 in answer_yes:
        print("\nYou are an honest person. He was a thief & You won the Game")

    elif ans2 in answer_no:
        print("\nYou helped a thief. Now, go to Jail. GAME OVER")

    else:
        print("\nYou typed the wrong input. GOODBYE!")

elif ans1 in answer_no:
    print("\nNow, he is trying to kill you. Will, you knock him down? (Yes / No)\n")

    ans3 = input(">>")

    if ans3 in answer_yes:
        print("\nCongrats! He was a thief & You helped the police to catch him with your bravery.")

    elif ans3 in answer_no:
        print("\nSorry! You are dead. He was a thief & He killed you. GAME OVER")

    else:
        print("\nYou typed the wrong input. GOODBYE!")

else:
    print("\nYou typed the wrong input. GOODBYE!")


WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)



>> yes



After 2 minutes, the Police came to your house, and ask you that whether the thief is in your house or not. Will you say (Yes / No)



>> yes



You are an honest person. He was a thief & You won the Game


In [18]:
#25. Build a program that solves a linear equation for x, considering different cases.
#ans:
def solve_linear(equation,var='x'):
    expression = equation.replace("=","-(")+")"
    grouped = eval(expression.replace(var,'1j'))
    return -grouped.real/grouped.imag
solve_linear("x-2*x+5*x-46*(235-24)=x+2")

3236.0

In [19]:
#26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.
#ans:
print("Wellcome to quiz game !!")
print('NOTE: if your spelling is incorrect then it is considered as wrong answer')
score = 0
question_no = 0
playing = input('Do you want to play ? ').lower()
if playing == 'yes':
    question_no += 1
    ques = input(f'\n{question_no}. what does CPU stand for? ').lower()
    if ques == 'central processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> central processing unit')

# ------1
    question_no += 1
    ques = input(f'\n{question_no}. what does GPU stand for? ').lower()
    
    if ques == 'graphics processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> graphics processing unit')

# -----2
    question_no += 1
    ques = input(f'\n{question_no}. what does RAM stand for? ').lower()
    
    if ques == 'random access memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> random access memory')

# -----3
    question_no += 1
    ques = input(f'\n{question_no}. what does PSU stand for? ').lower()
    
    if ques == 'power supply unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> power supply unit')


# -----4
    question_no += 1
    ques = input(f'\n{question_no}. what does ROM stand for? ').lower()
    
    if ques == 'read only memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> read only memory')


# ------5 

else:
    print('thankyou you are out of a game.')
    quit()

print(f'\nnumber of question is {question_no}')
print(f'your score is {score}')
try:
    percentage = (score *100)/question_no
except ZeroDivisionError:
    print('0% quetions are correct')

print(f'{percentage}% questions are correct.')

Wellcome to quiz game !!
NOTE: if your spelling is incorrect then it is considered as wrong answer


Do you want to play ?  yes

1. what does CPU stand for?  central processing unit


correct! you got 1 point



2. what does GPU stand for?  graphiacal processing unit


Incorrect!
current answer is --> graphics processing unit



3. what does RAM stand for?  random access memory


correct! you got 1 point



4. what does PSU stand for?  


Incorrect!
current answer is --> power supply unit



5. what does ROM stand for?  random of memory


Incorrect!
current answer is --> read only memory

number of question is 5
your score is 2
40.0% questions are correct.


In [28]:
#27. Develop a program that determines whether a given year is a prime number or not.
from math import sqrt

# Number to be checked for prime
n =int(input("enter the number"))

flag = 0

if(n > 1):
	for k in range(2, int(sqrt(n)) + 1):
		if (n % k == 0):
			flag = 1
		break
	if (flag == 0):
		print(n," is a Prime Number!")
	else:
		print(n," is Not a Prime Number!")
else:
	print(n," is Not a Prime Number!")

enter the number 16


16  is Not a Prime Number!


In [29]:
#28. Create a program that sorts three numbers in ascending order using conditional statements.
#ans:
# Prompt the user to enter three numbers
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))

# Sort the numbers in ascending order
if num1 <= num2 and num1 <= num3:
    smallest = num1
    if num2 <= num3:
        middle = num2
        largest = num3
    else:
        middle = num3
        largest = num2
elif num2 <= num1 and num2 <= num3:
    smallest = num2
    if num1 <= num3:
        middle = num1
        largest = num3
    else:
        middle = num3
        largest = num1
else:
    smallest = num3
    if num1 <= num2:
        middle = num1
        largest = num2
    else:
        middle = num2
        largest = num1

# Print the sorted numbers in ascending order
print("Sorted numbers in ascending order:", smallest, middle, largest)

Enter the first number:  10
Enter the second number:  5
Enter the third number:  4


Sorted numbers in ascending order: 4 5 10


In [32]:
#29. Build a program that determines the roots of a quartic equation using numerical methods.
#ans:
# Python program to find roots
# of a quadratic equation
import math
 
# Prints roots of quadratic equation
# ax*2 + bx + x
def findRoots(a, b, c):
 
    # If a is 0, then equation is
    # not quadratic, but linear
    if a == 0:
        print("Invalid")
        return -1
    d = b * b - 4 * a * c
    sqrt_val = math.sqrt(abs(d))
 
    if d > 0:
        print("Roots are real and different ")
        print((-b + sqrt_val)/(2 * a))
        print((-b - sqrt_val)/(2 * a))
    elif d == 0:
        print("Roots are real and same")
        print(-b / (2*a))
    else:  # d<0
        print("Roots are complex")
        print(- b / (2*a), " + i", sqrt_val / (2 * a))
        print(- b / (2*a), " - i", sqrt_val / (2 * a))
 
 
# Driver Program
if __name__ == '__main__':
    a = 1
    b = -7
    c = 12
     
    # Function call
    findRoots(a, b, c)
 

Roots are real and different 
4.0
3.0


In [33]:
'''#30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based
on the user's input.'''
#ans:
def bodymassindex(height,weight):
    return round((weight / height**2),2)


h = float(input("Enter your height in meters: "))
w = float(input("Enter your weight in kg: "))


print("Welcome to the BMI calculator.")

bmi = bodymassindex(h, w)
print("Your BMI is: ", bmi)


if bmi <= 18.5:
    print("You are underweight.")
elif 18.5 < bmi <= 24.9:
    print("Your weight is normal.")
elif 25 < bmi <= 29.29:
    print("You are overweight.")
else:
    print("You are obese.")

Enter your height in meters:  170
Enter your weight in kg:  74


Welcome to the BMI calculator.
Your BMI is:  0.0
You are underweight.


In [35]:
###Challenge Level:

In [37]:
'''31. Create a program that validates a password based on complexity rules (length, characters, etc.).'''
#ans:
import string
import random
#getting password length
length=int(input("enter the password length :"))
print('''choice character set for a pasword from these:
          1.Letters
          2.Special characters
          3.Digits
          4.exit''')
characterList=""
#getting charcter set  password
while(True):
    choice = int(input("pick a number :"))
    if (choice==1):
        
        #adding letters to possible characters
        characterList+=string.ascii_letters
    elif(choice==2):
        
        #adding special characters to possible
        #characters
        characterList+=string.punctuation
    elif(choice==3):
        #adding special characters to possible
        #characters
        characterList+=string.digits
    elif(choice==4):
        break
    else:
        print("please pick a valid optional!")
        
        
password=[]
for i in range(length):
    randomchar=random.choice(characterList)
    password.append(randomchar)
print("the random password is : " +"".join(password))

enter the password length : 10


choice character set for a pasword from these:
          1.Letters
          2.Special characters
          3.Digits
          4.exit


pick a number : 2
pick a number : 5


please pick a valid optional!


pick a number : 4


the random password is : (};\'.,.}{


In [54]:
#32. Develop a program that performs matrix addition and subtraction based on user input.
#ans:
# Python program to add and subtract two matrix

# take first matrix inputs
m1 = [list(map(int, input("Enter row: ").split(" ")))
      for i in range(int(input("Enter Number of rows: ")))]

# take second matrix inputs
m2 = [list(map(int, input("Enter row: ").split(" ")))
      for i in range(int(input("Enter Number of rows:")))]

# add these matrix
print("Add Matrix:")
r = [[m1[i][j] + m2[i][j]
      for j in range(len(m1[0]))] for i in range(len(m1))]
print(r)

# subtract these matrix
print("Subtract Matrix:")
r = [[m1[i][j] - m2[i][j]
      for j in range(len(m1[0]))] for i in range(len(m1))]
print(r)

Enter Number of rows:  2
Enter row:  9 8
Enter row:  7 6
Enter Number of rows: 2
Enter row:  5 4
Enter row:  3 2


Add Matrix:
[[14, 12], [10, 8]]
Subtract Matrix:
[[4, 4], [4, 4]]


In [56]:
'''#33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
algorithm.'''
#ans:
# Recursive function to return gcd of a and b
def gcd(a, b):

	# Everything divides 0
	if (a == 0):
		return b
	if (b == 0):
		return a

	# base case
	if (a == b):
		return a

	# a is greater
	if (a > b):
		return gcd(a-b, b)
	return gcd(a, b-a)

# Driver program to test above function
a = 98
b = 56
if(gcd(a, b)):
	print('GCD of', a, 'and', b, 'is', gcd(a, b))
else:
	print('not found')



GCD of 98 and 56 is 14


In [57]:
#34. Build a program that performs matrix multiplication using nested loops and conditional statements.
#ans:
# Program to multiply two matrices using list comprehension

# take a 3x3 matrix
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]

# result will be 3x4
result = [[sum(a * b for a, b in zip(A_row, B_col)) 
						for B_col in zip(*B)]
								for A_row in A]

for r in result:
	print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [58]:
#35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.
#ans:
# Tic-Tac-Toe Program using
# random number in Python

# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board


def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board


def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player


def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

# Checks whether the player has three
# of their marks in a horizontal row


def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row


def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row


def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie


def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game


def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


# Driver Code
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Board after 2 move
[[2 0 0]
 [0 0 0]
 [0 1 0]]
Board after 3 move
[[2 0 0]
 [0 0 0]
 [1 1 0]]
Board after 4 move
[[2 0 0]
 [0 0 2]
 [1 1 0]]
Board after 5 move
[[2 0 0]
 [0 1 2]
 [1 1 0]]
Board after 6 move
[[2 0 0]
 [0 1 2]
 [1 1 2]]
Board after 7 move
[[2 0 0]
 [1 1 2]
 [1 1 2]]
Board after 8 move
[[2 2 0]
 [1 1 2]
 [1 1 2]]
Board after 9 move
[[2 2 1]
 [1 1 2]
 [1 1 2]]
Winner is: 1


In [60]:
#36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.
num = 10
n1, n2 = 0, 1
print("Fibonacci Series:", n1, n2, end=" ")
for i in range(2, num):
    n3 = n1 + n2
    n1 = n2
    n2 = n3
    print(n3, end=" ")

print()

Fibonacci Series: 0 1 1 2 3 5 8 13 21 34 


In [61]:
#37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.
#ans:
# Function for nth Fibonacci number

def Fibonacci(n):
	if n<= 0:
		print("Incorrect input")
	# First Fibonacci number is 0
	elif n == 1:
		return 0
	# Second Fibonacci number is 1
	elif n == 2:
		return 1
	else:
		return Fibonacci(n-1)+Fibonacci(n-2)

# Driver Program

print(Fibonacci(10))


34


In [62]:
#38. Create a program that generates a calendar for a given month and year using conditional statements.
#ans:
# Program to display calendar of the given month and year

# importing calendar module
import calendar

yy = 2014  # year
mm = 11    # month

# To take month and year input from the user
# yy = int(input("Enter year: "))
# mm = int(input("Enter month: "))

# display the calendar
print(calendar.month(yy, mm))

   November 2014
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30



In [63]:
#39. Build a program that simulates a basic text-based blackjack game against the computer.
#ans:
import random 

card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades'] 
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King'] 
deck = [(card, category) for category in card_categories for card in cards_list] 

def card_value(card): 
	if card[0] in ['Jack', 'Queen', 'King']: 
		return 10
	elif card[0] == 'Ace': 
		return 11
	else: 
		return int(card[0]) 

random.shuffle(deck) 
player_card = [deck.pop(), deck.pop()] 
dealer_card = [deck.pop(), deck.pop()] 

while True: 
	player_score = sum(card_value(card) for card in player_card) 
	dealer_score = sum(card_value(card) for card in dealer_card) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("\n") 
	choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower() 
	if choice == "play": 
		new_card = deck.pop() 
		player_card.append(new_card) 
	elif choice == "stop": 
		break
	else: 
		print("Invalid choice. Please try again.") 
		continue

	if player_score > 21: 
		print("Cards Dealer Has:", dealer_card) 
		print("Score Of The Dealer:", dealer_score) 
		print("Cards Player Has:", player_card) 
		print("Score Of The Player:", player_score) 
		print("Dealer wins (Player Loss Because Player Score is exceeding 21)") 
		break

while dealer_score < 17: 
	new_card = deck.pop() 
	dealer_card.append(new_card) 
	dealer_score += card_value(new_card) 

print("Cards Dealer Has:", dealer_card) 
print("Score Of The Dealer:", dealer_score) 
print("\n") 

if dealer_score > 21: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)") 
elif player_score > dealer_score: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("Player wins (Player Has High Score than Dealer)") 
elif dealer_score > player_score: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("Dealer wins (Dealer Has High Score than Player)") 
else: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("It's a tie.")


Cards Player Has: [('10', 'Diamonds'), ('3', 'Diamonds')]
Score Of The Player: 13




What do you want? ["play" to request another card, "stop" to stop]:  stop


Cards Dealer Has: [('10', 'Hearts'), ('8', 'Clubs')]
Score Of The Dealer: 18


Cards Dealer Has: [('10', 'Hearts'), ('8', 'Clubs')]
Score Of The Dealer: 18
Cards Player Has: [('10', 'Diamonds'), ('3', 'Diamonds')]
Score Of The Player: 13
Dealer wins (Dealer Has High Score than Player)


In [64]:
#40. Write a program that generates the prime factors of a given number using trial division.
#ans:
# Python3 implementation of 
# Trial Division Algorithm

# Function to check if a number is
# a prime number or not 
def TrialDivision(N):

	# Initializing with the value 2 
	# from where the number is checked
	i = 2

	# Computing the square root of 
	# the number N
	k = int(N ** 0.5)

	# While loop till the 
	# square root of N
	while(i<= k):

		# If any of the numbers between 
		# [2, sqrt(N)] is a factor of N 
		# Then the number is composite
		if(N % i == 0):
			return 0
		i += 1

	# If none of the numbers is a factor,
	# then it is a prime number
	return 1
	
# Driver code
if __name__ == "__main__":
	N = 49
	p = TrialDivision(N)

# To check if a number is a prime or not
	if(p):
		print("Prime")
	else:
		print("Composite")
		


Composite
